### ISSUE TITLE
Error with MandiantAzureADInvestigator.psd1

### ISSUE THREAD

**Issue by cdev45** [fireeye/Mandiant-Azure-AD-Investigator#3]
I downloaded the full ZIP, extracted and confirmed all Microsoft Powershell modules are installed. When attempting to run the first command "Import-Module MandiantAzureADInvestigator.psd1", I am receiving the following error:

PS C:\temp\Mandiant-Azure-AD-Investigator-master> Import-Module MandiantAzureADInvestigator.psd1
Import-Module : The specified module 'MandiantAzureADInvestigator.psd1' was not loaded because no valid module file
was found in any module directory.
At line:1 char:1
Import-Module MandiantAzureADInvestigator.psd1
CategoryInfo          : ResourceUnavailable: (MandiantAzureADInvestigator.psd1:String) [Import-Module], FileNotFoundException
FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by dsmith955** [comment]
You need to add the Mandiant folder to your PS module path and then run the Import Module command.

**Comment by jskiba99** [comment]
I received this error and got by it by specifying the full path. In your case:

Import-Module C:\temp\Mandiant-Azure-AD-Investigator-master\MandiantAzureADInvestigator.psd1

**Comment by dmb2168** [comment]
Yes you either need to add the folder to your PS module path, and then you can import it just by name 'MandiantAzureADInvestigator'
OR
make sure your current working directory is the same directory that contains all the PS files.

**Comment by FernandoGualano** [comment]
Hi! 
I have the same problem when I try to run this command: Import-Module MandiantAzureADInvestigator.psd1

![image](https://user-images.githubusercontent.com/50090959/106000217-58b76000-608d-11eb-851c-c44eff517686.png)

I copied the Mandiant-Azure-AD-Investigator folder to PS Module path:

![image](https://user-images.githubusercontent.com/50090959/106000412-8c928580-608d-11eb-965b-207004a60dc0.png)

However, I received the same error. 

Any idea? Thanks!!

**Comment by dmb2168** [comment]
If you've copied it into the PS Module path, once you start a new PowerShell session you should be able to reference the module by name only, e.q.

`Import-Module  MandiantAzureADInvestigator`

It should tab auto-complete for you as well.

**Comment by dr-raypc** [comment]
Running into an error message when searching for Update Applications, see below.


Search for 'Update Application' events
Get-MandiantBulkUAL : The result index is greater than the result count. Rerunning the query
At line:1 char:1
+ Get-MandiantBulkUAL -Operations 'Update application' -DateOffset 90 - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-MandiantBulkUAL

**Comment by vandelay77** [comment]
So, I am having the same issue. I have tried cd to the folder as well as placing it in the powershell modules folder. Has anyone resolved this? I am running powershell 5.1 as administrator. I am not sure where to go from here...

**Comment by jskiba99** [comment]
@FernandoGualano
See the required module in that error message. Earlier in the README directions it points out to install 3 other modules: AzureAD, MSOnline and ExchangeOnlineManagement.

@vandelay77
If you follow the directions and cd into the extracted folder prefix the module file name with ```.\```
```Import-Module .\MandiantAzureADInvestigator.psd1```

You can also specificy the fully qualified path the file.
```Import-Module c:\temp\Mandiant-Azure-AD-Investigator\MandiantAzureADInvestigator.psd1```

@dmb2168 
If you copy the folder into your powershell modules directory, the hyphens need removed from the git repo folder name so the folder name matches the module files name.  This is shown in your example here, but wouldn’t for others if they just copy the repo folder to the modules directory.

```Import-Module MandiantAzureADInvestigator```

**Comment by dmb2168** [comment]
Closing, jskiba99 solution is the winner.
