### ISSUE TITLE
No CSV file generated

### ISSUE THREAD

**Issue by GeoCookie** [fireeye/Mandiant-Azure-AD-Investigator#4]
Hi,

After running the script, I get many json files and a txt file, but no CSV. I expected one, as indicated on the doc
`6. Review the output on the screen and the written CSV files.`
On the output of the script, I don't have a line starting with "!!", like
`!! A token signing certificate has a validity period of more than 365 days. `

Does that mean everything is fine on my tenant ?

**Comment by dmb2168** [comment]
If the script did not find anything notable, then it will not generate any corresponding CSV files

**Comment by GeoCookie** [comment]
Good news. Thank you
