### ISSUE TITLE
Partner Office 365 Account | Only one customer is checked? 

### ISSUE THREAD

**Issue by samredinet** [fireeye/Mandiant-Azure-AD-Investigator#5]
Running the script with Office 365 Partner credentials, I was expected the Azure test to go through each customer and run the same checks for each customer, however it has only listed one?

Is this a feature that can be added, instead of running the script 20/30 times, with individual global admin credentials. 
My office 365 partner account has global admin rights for all customers.

**Comment by dmb2168** [comment]
The script is built to connect to only one tenant and run the checks. It should be relatively straightforward for you to use PowerShell to make a FOR loop that disconnects/reconnects to all of the tenants in a list.

**Comment by samredinet** [comment]
Thanks Doug,

I will take a look at that and let you know

Thanks
Sam
